### PR TITLE
context menu to open in jcef

### PR DESCRIPTION
**Pull request by liudongmiao**
add context menu to open pdf in jcef (named "Open in Embedded Browser").

would close https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/113

### CODE REVIEW

**Review by PHPirates — APPROVED** [review]
Nice! I think this is a good unobtrusive way to easily open in the browser. I did need to disable OSR to get a context menu: https://youtrack.jetbrains.com/issue/IJPL-59459/Context-menu-does-not-work-for-OSR-Cef-browser

**Comment by liudongmiao** [comment]
I'm using the IDEA 2024.2, and Clion 2024.1, both with OSR enabled, and the context menu is displayed in both IDEs.

As it's a experimental features, so I don't think a context menu should be enough.

**Comment by liudongmiao** [comment]
@PHPirates before releases, we should check open issues (as we have latest pdf.js):
#41 #48 should be enhanced easily, #100 #101 should be fixed
#31 should be double checked (viewer use development, it should be easy to find)
#52 should be double checked, whether is bug or enhancement, as we support virtual file now
#80 should be double checked

**Comment by PHPirates** [comment]
Yeah that's true I'll have a look if these are still an issue.

**Comment by liudongmiao** [comment]
@PHPirates After merging #119, there are still some issues.
However, I think they are minor issues which I'm not familiar with, I have no plan to create PR.

**Comment by PHPirates** [comment]
I will create a release today. Thanks so much for your help! The next few months I should have time again to look at some issues on the intellij plugin side of things.

**Pull request merged**
